In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

In [3]:
#!head training_data.csv

'head' is not recognized as an internal or external command,
operable program or batch file.

In [4]:
training_data = pd.read_csv('training_data.csv')

In [5]:
training_data

,sa_citizen,special_needs,caregiver_treatment,appliance,plaque,dry_mouth,enamel_defects,fluoride_water,fluoride_toothpaste,topical_fluoride,...,dairy_products_weekly,vegetables,vegetables_daily,vegetables_weekly,water,water_timing,water_glasses,has_dental_data,has_dietary_data,risk_level
0,1,0,1,1,1,0,1,0,0,1,...,0,0,0,0,0,0,0,1,1,low
1,1,0,1,1,1,0,0,0,1,1,...,0,1,1,1,0,0,0,1,1,medium
2,1,1,0,1,0,0,1,1,0,0,...,3,0,0,0,1,1,4,1,1,low
3,0,0,0,1,1,0,0,0,0,0,...,1,0,0,0,1,3,3,1,1,low
4,0,1,0,1,1,0,0,0,1,1,...,0,0,0,0,0,0,0,1,1,medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,0,0,1,1,1,1,1,0,0,1,...,3,1,0,4,0,0,0,1,1,high
19996,0,1,1,0,1,0,1,0,1,0,...,2,1,3,2,1,3,3,1,1,low
19997,0,1,0,0,1,0,1,0,1,1,...,4,0,0,0,1,2,4,1,1,high
19998,1,0,0,0,1,0,1,1,0,1,...,4,1,1,3,0,0,0,1,1,medium
19999,0,1,0,0,1,0,0,0,1,0,...,0,0,0,0,1,1,3,1,1,low